version: "1.0"
info:
  model: int-scaffold
packages:
- name: DADATestProject
  gitServerName: DADATest
  gitUrl: https://github.com/HCLwMCOE
  gitUsername: HCLwMCOE
  gitBranch: main
services:
- serviceName: project.dadatest.integrations:helloWorld
  packages:
  - name: DADATestProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.dadatest.integrations:multiplyInts
  packages:
  - name: DADATestProject
    version: "1.0"
- serviceName: pub.math:multiplyInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
